name: runipet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/pet/dog/stage_1_egg/
    - assets/images/pet/dog/stage_2_hatch/
    - assets/images/pet/dog/stage_3_child/
    - assets/images/pet/dog/stage_4_adult/
    - assets/images/pet/dog/stage_5_elder/
    - assets/images/pet/cat/stage_1_egg/
    - assets/images/pet/cat/stage_2_hatch/
    - assets/images/pet/cat/stage_3_child/
    - assets/images/pet/cat/stage_4_adult/
    - assets/images/pet/cat/stage_5_elder/
    - assets/images/pet/rabbit/stage_1_egg/
    - assets/images/pet/rabbit/stage_2_hatch/
    - assets/images/pet/rabbit/stage_3_child/
    - assets/images/pet/rabbit/stage_4_adult/
    - assets/images/pet/rabbit/stage_5_elder/
