name: runipet
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  fl_chart: ^0.66.0
  permission_handler: ^11.1.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  path_provider: ^2.1.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/items/
    - assets/images/pet/dog/stage_1_egg/
    - assets/images/pet/dog/stage_2_hatch/
    - assets/images/pet/dog/stage_3_child/
    - assets/images/pet/dog/stage_4_adult/
    - assets/images/pet/dog/stage_5_elder/
    - assets/images/pet/cat/stage_1_egg/
    - assets/images/pet/cat/stage_2_hatch/
    - assets/images/pet/cat/stage_3_child/
    - assets/images/pet/cat/stage_4_adult/
    - assets/images/pet/cat/stage_5_elder/
    - assets/images/pet/rabbit/stage_1_egg/
    - assets/images/pet/rabbit/stage_2_hatch/
    - assets/images/pet/rabbit/stage_3_child/
    - assets/images/pet/rabbit/stage_4_adult/
    - assets/images/pet/rabbit/stage_5_elder/